name: CI example 
on: 
  push:
        branches: main
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Integration/Unit Test
        run: mvn test
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Copy artifact to staging directory
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging